### ISSUE TITLE
mutate() loses groups

### ISSUE THREAD

**Issue by hadley** [hadley/dtplyr#17]
Moved from https://github.com/hadley/dplyr/issues/919, by kykuo

``` R
library(dplyr)
library(dtplyr)

iris %>%
  group_by(Species) %>% 
  mutate(x = cumsum(Sepal.Length)) %>% 
  groups

data.table::data.table(iris) %>% 
  group_by(Species) %>%
  mutate(x = cumsum(Sepal.Length)) %>%
  groups
```

**Comment by HuangNa2** [comment]
Seems like mutate reduces the group by 1 everytime its called
```
library(dplyr)
library(dtplyr)

iris %>%
  group_by(Species,Petal.Width,Sepal.Length) %>% 
  mutate(x = cumsum(Sepal.Length)) %>% 
  groups
```

Results in : 

[[1]]
Species

[[2]]
Petal.Width

From a bit of testing it appears that it removes the last grouped element each time mutate is called.
