### ISSUE TITLE
Tests fail on Travis but work locally

### ISSUE THREAD

**Issue by krlmlr** [hadley/dtplyr#2]
irrespective of data.table version: https://travis-ci.org/krlmlr/dtplyr/builds/114494008#L1552-L1555

```
  1. Error: distinct removes duplicates (data.table) 
  2. Error: distinct removes duplicates (tbl_dt) 
  3. Error: grouped_by uses grouping vars & preserves groups 
  4. Error: ungrouped data table with unnamed argument returns data table 
```

Working on replicating the Travis build environment (Ubuntu Precise) in a Docker container.

**Comment by hadley** [comment]
Yeah, it's because I accidentally depended on dev testthat. Now fixed.
