### ISSUE TITLE
Inconsistent output using distinct without specifying columns

### ISSUE THREAD

**Issue by tony-stone** [hadley/dtplyr#25]
Perhaps more an omission in documentation but, `dplyr::left_join` etc. and `dplyr::distinct()` set/use keys when working with `data.table`s.

Thus one gets very different results running the same dplyr commands depending on whether one is using `data.table` or plain `data.frame`s

<details>
<summary>Reprex</summary>

```
library(data.table)
library(dplyr)

df1 <- data.frame(id1 = LETTERS[1:4], id2 = rep(1:2, 2), stringsAsFactors = FALSE)
df2 <- data.frame(id2 = 1:2, val = letters[1:2], stringsAsFactors = FALSE)

dt1 <- data.table(df1)
dt2 <- data.table(df2)

df <- left_join(df1, df2, by = "id2") %>% distinct()
dt <- left_join(dt1, dt2, by = "id2") %>% distinct()
```

plain data.fame result:

```
dput(df)
structure(list(id1 = c("A", "B", "C", "D"), id2 = c(1L, 2L, 1L, 
2L), val = c("a", "b", "a", "b")), class = "data.frame", row.names = c(NA, 
-4L), .Names = c("id1", "id2", "val"))
```

data.table result:

```
dput(dt)
structure(list(id2 = 1:2, id1 = c("A", "B"), val = c("a", "b"
)), sorted = "id2", class = c("tbl_dt", "tbl", "data.table", 
"data.frame"), row.names = c(NA, -2L), .internal.selfref = <pointer: 0x0000000000100788>, .Names = c("id2", 
"id1", "val"))
```
</details>

A simple fix would be to set key to null when no arguments are passed into `distinct()`.

However, the above and *_join() have the effect of altering the key-/index-ing of a user's `data.table` without this being made explicit to the user.

An inefficient fix for dtplyr methods which re-key data.tables might be if dtplyr recorded the data.table's key(s) before any operation and then reset them after.

But, I doubt there is a good/efficient fix to this other than to better document this.

**Comment by hadley** [comment]
Updated reprex:

``` r
library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

df1 <- data.frame(id1 = LETTERS[1:4], id2 = rep(1:2, 2), stringsAsFactors = FALSE)
df2 <- data.frame(id2 = 1:2, val = letters[1:2], stringsAsFactors = FALSE)
df1 %>% left_join(df2, by = "id2") %>% distinct()
#>   id1 id2 val
#> 1   A   1   a
#> 2   B   2   b
#> 3   C   1   a
#> 4   D   2   b

dt1 <- data.table(df1)
dt2 <- data.table(df2)
dt1 %>% left_join(dt2, by = "id2") %>% distinct()
#> Source: local data table [4 x 3]
#> 
#> # A tibble: 4 x 3
#>     id2 id1   val  
#>   <int> <chr> <chr>
#> 1     1 A     a    
#> 2     1 C     a    
#> 3     2 B     b    
#> 4     2 D     b
```

<sup>Created on 2019-06-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
Because the joins no longer use `setkey()`, this problem has gone away.  The columns/rows are not in the same order, but I think that's ok. (And if not, it's a buglet with the joins).
