### ISSUE TITLE
Add setOldClass

### ISSUE THREAD

**Issue by krlmlr** [hadley/dtplyr#26]
`setOldClass(c("tbl_dt", "data.frame"))`

https://github.com/hadley/dplyr/issues/969#issuecomment-157873870

**Comment by hadley** [comment]
Should be `setOldClass(c("tbl_dt", "data.table", "data.frame"))` right?

**Comment by krlmlr** [comment]
data.table already does part of that: https://github.com/Rdatatable/data.table/blob/431b7081ef48dd7a603d456f710510f6277bd239/R/AllS4.R#L6-L7 . Honestly, I don't know what's best here.
