### ISSUE TITLE
tbl_df loses types of columns when accessing the old fashioned way

### ISSUE THREAD

**Issue by svannoy** [hadley/dtplyr#28]
I've written a function that takes a data.frame and a character vector indicating which column should be operated on. The function needs to know the class of the column. It works fine when I pass in a data.frame, but if I pass in a tbl_df, the class information is lost. I've got a work around, which is:

```
 if ( "tbl_df" %in% class(x))
{
x <- as.data.frame(x)
}
```

But, this seems less than desirable ultimately.

Here is a reproducible example:

```
 library(dplyr)
x <- data.frame(numericVar = c(1.1, 2.2, 3.3))
class(x$numericVar)
class(x[,"numericVar"])

x <- tbl_df(x)
class(x$numericVar)
class(x[,"numericVar"])

```

**Comment by hadley** [comment]
I don't think this is the right repo, but if you want to extract a single column, use `[[`.

**Comment by svannoy** [comment]
Oops, sorry about that, meant to go to dplyr.

Thanks, that works.
