### ISSUE TITLE
.GTP yields NA

### ISSUE THREAD

**Issue by ghost** [hadley/dtplyr#35]
This example 

```
data.table(a=rnorm(10),b=rep(0:1, 5))  %>% group_by(b) %>% mutate(g=.GRP)
```

gives me the following error:

```
Error: Unsupported type NILSXP for column "g"
```

**Comment by krlmlr** [comment]
What is this code supposed to do?

**Comment by rafstraumur** [comment]
It adds the index of every group to the table. So every b=0 gets a 1 and every b=1 gets a 2. It works with dplyr_0.4.3 , but not with dplyr_0.5.0

**Comment by hadley** [comment]
In general, I don't think you should expect data table pronouns to work inside dplyr verbs; dplyr verbs support dplyr pronouns.
