### ISSUE TITLE
dtplyr fails to load dependencies

### ISSUE THREAD

**Issue by PReineke** [hadley/dtplyr#39]
Today my dtplyr suddenly stopped loading its dplyr and data.table dependencies after I restarted R. After calling library(dtplyr), none of the dplyr or data.table functions work. I have been using dtplyr for several weeks before (thanks a LOT for creating this package!) and it was working without a hitch so far. All other libraries are still loading their respective dependencies. Also dtplyr and data.table load correctly when called separately.

I am using Microsoft R Open 3.3.2 in RStudio on MacOSX 10.11.6

My Session after loading dtplyr looks as follows:
```
> library(dtplyr)
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dtplyr_0.0.1

loaded via a namespace (and not attached):
[1] magrittr_1.5     R6_2.2.0         assertthat_0.1   RevoUtils_10.0.2 DBI_0.5-1       
[6] tools_3.3.2      dplyr_0.5.0      tibble_1.2       Rcpp_0.12.7
```     

I restarted R, restarted R Studio, re-installed dtplyr, updated dplyr and data.table, and completely reinstalled Microsoft R Open, none of which solved the problem. Before the error occurred I was trying out different parallel processing commands and packages for the first time (doMC, doSNOW, doParallel), so I assume that might have something to do with the issue.

Any idea what could be causing this issue? Please let me know if I should provide additional data.

**Update:**
Installing the developer version of dtplyr via devtools::install_github("hadley/dtplyr") solved the issue temporarily. However, after running the functions

```
> cl <- makeCluster(detectCores()-1)
> registerDoParallel(cl)
> x <- foreach(i = 1:z, .combine = rbind) %dopar% { some_dplyr_code }
```

the foreach function failed with the error message

> Error in { : task 1 failed - "could not find function "%>%""

and now I have the same issue again (dtplyr does not load dplyr or data table).

**Comment by brigoodwinan** [comment]
I have the same problem. Please fix! :)

**Comment by hadley** [comment]
As far as I remember, it never automatically loaded dplyr and data.table; you need to load them explicitly yourself.
