### ISSUE TITLE
register_s3_method loads package

### ISSUE THREAD

**Issue by wch** [hadley/dtplyr#60]
The version of `register_s3_method` currently used in dtplyr tries to load the load the `pkg`, because it calls `asNamespace(pkg)` early on.

https://github.com/hadley/dtplyr/blob/2308ff25e88bb81fe84f9051e37ddd9d572189ee/R/compat-dplyr-0.6.0.R#L77

Also, later in that function, it does `if (pkg %in% loadedNamespaces())` and `setHook(packageEvent(pkg, "onLoad"), ... )`, which are both redundant, because the package must be loaded by that point.

In practice for dtplyr, this doesn't cause any problems, because the only package that's used is dplyr, which is an Import and will always already be loaded. However, for package authors that borrow this code (like me), the `asNamespace(pkg)` can cause problems: it loads the `pkg`, which it shouldn't, and if `pkg` isn't installed, then the function errors out -- which is a showstopper if `register_s3_method` is called from `.onLoad()`.

**Comment by lionel-** [comment]
@hadley this seems relevant for vctrs registration.

**Comment by hadley** [comment]
`register_s3_method()` will be removed as part of #68
