### ISSUE TITLE
"Invalid .internal.selfref detected" - using bind_rows loses over allocation

### ISSUE THREAD

**Issue by emilBeBri** [hadley/dtplyr#64]
Hi

I get the warning:

Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can add this new column by reference. At an earlier point, this data.table has been copied by R (or was created manually using structure() or similar). Avoid key<-, names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. If this message doesn't help, please report your use case to the data.table issue tracker so the root cause can be fixed or this message improved.

when creating a new variable by reference, on a data.table that, at least as far as I can tell, is just a normal data.table:

library(dplyr)
library(data.table)

a1 <- data.table(v1=c(1:10), v2=rep('A'))
a2 <- data.table(v1=c(1:10), v2=rep('B'))
a3 <- Reduce(bind_rows,list(a1,a2))
a3[, n_max:=.N, by=v2]

I do not get the same warning when using the '[, n_max:=.N, by=v2]' syntax on either a1 or a2. 

[According to these guys over at data.table](https://github.com/Rdatatable/data.table/issues/3274), where I originally raised the issue, the problem is in bind_rows, and not in data.table:

> Using bind_rows loses over allocation. That results into warning later on when using :=. You can track that using truelength function.

```
library(dplyr)
library(data.table)
a1 <- data.table(v1=c(1:10), v2=rep('A'))
a2 <- data.table(v1=c(1:10), v2=rep('B'))
a3 <- Reduce(bind_rows,list(a1,a2))
a4 <- Reduce(rbind,list(a1,a2))
a5 <- rbindlist(list(a1,a2))
truelength(a3)
#[1] 0
truelength(a4)
#[1] 1026
truelength(a5)
#[1] 1026
```

Greetings, 
Emil

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.10

Matrix products: default
BLAS/LAPACK: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin/libmkl_rt.so

locale:
 [1] LC_CTYPE=en_DK.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_DK.UTF-8        LC_COLLATE=en_DK.UTF-8    
 [5] LC_MONETARY=en_DK.UTF-8    LC_MESSAGES=en_DK.UTF-8   
 [7] LC_PAPER=en_DK.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_DK.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.11.8 dplyr_0.7.8      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       crayon_1.3.4     assertthat_0.2.0 R6_2.3.0        
 [5] magrittr_1.5     pillar_1.3.1     rlang_0.3.0.1    bindrcpp_0.2.2  
 [9] glue_1.3.0       purrr_0.2.5      compiler_3.5.1   pkgconfig_2.0.2 
[13] colorspace_1.3-2 bindr_0.1.1      tidyselect_0.2.5 tibble_1.4.2  
```

**Comment by hadley** [comment]
The code runs without errors for me:

``` r
library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

a1 <- data.table(v1=c(1:10), v2=rep('A'))
a2 <- data.table(v1=c(1:10), v2=rep('B'))
a3 <- Reduce(bind_rows,list(a1,a2))
a4 <- Reduce(rbind,list(a1,a2))
a5 <- rbindlist(list(a1,a2))
truelength(a3)
#> [1] 0
truelength(a4)
#> [1] 1026
truelength(a5)
#> [1] 1026
```

<sup>Created on 2019-05-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
