### ISSUE TITLE
rename_all broken

### ISSUE THREAD

**Issue by vspinu** [hadley/dtplyr#65]
When `dtplyr` is loaded `rename_all` suddenly breaks:

```R
library(dplyr)
library(dtplyr)
library('data.table')
dplyr::rename_all(as.data.table(Orange), identity)
## Error: All arguments must be named
## Call `rlang::last_error()` to see a backtrace
```

<details>
+ Error: All arguments must be named
[90mCall `rlang::last_error()` to see a backtrace[39m
 
---------------------------------- 

10: stop(cnd) at cnd.R#388
9: abort("All arguments must be named") at vars-rename.R#12
8: tidyselect::vars_rename(.vars = vars, ..., .strict = strict) at reexport-tidyselect.R#70
7: rename_vars(vars, !!!args) at reexport-tidyselect.R#114
6: dplyr::rename_vars_(names(.data), dots) at tbl-dt.r#306
5: rename_.data.table(.data, .dots = lazyeval::lazy_dots(...)) at manip.r#730
4: rename_(.data, .dots = lazyeval::lazy_dots(...)) at tbl-dt.r#291
3: rename.data.table(.tbl, !!!syms) at manip.r#713
2: rename(.tbl, !!!syms) at colwise-select.R#60
1: dplyr::rename_all(as.data.table(Orange), identity)

devtools::session_info()
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                                             
 version  R Under development (unstable) (2018-12-01 r75733)
 os       Ubuntu 18.04.1 LTS                                
 system   x86_64, linux-gnu                                 
 ui       X11                                               
 language                                                   
 collate  en_GB.UTF-8                                       
 ctype    en_GB.UTF-8                                       
 tz       Asia/Shanghai                                     
 date     2019-02-28                                        

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date       lib source                          
 assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.0)                  
 backports     1.1.2      2017-12-13 [1] CRAN (R 3.5.0)                  
 callr         3.0.0.9002 2018-12-03 [1] Github (r-lib/callr@1cbce9d)    
 cli           1.0.1      2018-09-25 [1] CRAN (R 3.6.0)                  
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.0)                  
 desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                  
 devtools      2.0.1.9000 2018-12-03 [1] Github (r-lib/devtools@a6bbe87) 
 digest        0.6.18     2018-10-10 [1] CRAN (R 3.6.0)                  
 fs            1.2.6      2018-08-23 [1] CRAN (R 3.6.0)                  
 glue          1.3.0      2018-07-17 [1] CRAN (R 3.6.0)                  
 magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.0)                  
 memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.0)                  
 pkgbuild      1.0.2.9000 2018-12-03 [1] Github (r-lib/pkgbuild@6e4ebdf) 
 pkgload       1.0.1.9000 2018-12-03 [1] Github (r-lib/pkgload@0ef4f58)  
 prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.0)                  
 processx      3.2.0.9001 2018-12-03 [1] Github (r-lib/processx@366475b) 
 ps            1.2.1      2018-11-06 [1] CRAN (R 3.6.0)                  
 R6            2.4.0      2019-02-14 [1] CRAN (R 3.6.0)                  
 Rcpp          1.0.0      2018-11-07 [1] CRAN (R 3.6.0)                  
 remotes       2.0.2.9000 2018-12-03 [1] Github (r-lib/remotes@2e3bf35)  
 rlang         0.3.1.9000 2019-02-19 [1] Github (r-lib/rlang@7243c6d)    
 rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                  
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                  
 testthat      2.0.0      2017-12-13 [1] CRAN (R 3.5.0)                  
 usethis       1.4.0      2018-08-14 [1] CRAN (R 3.6.0)                  
 withr         2.1.2.9000 2018-10-23 [1] Github (jimhester/withr@be57595)

[1] /home/vspinu/.lib/3.6.0
[2] /home/vspinu/bin/R-latest/library
> 
</details>

**Comment by lionel-** [comment]
Unfortunately dtplyr is not in a usable state currently. We plan to revisit the package implementation sometimes this year.

**Comment by hadley** [comment]
Looks like this is working again now

``` r
library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

rename_all(as.data.table(Orange), identity)
#>     Tree  age circumference
#>  1:    1  118            30
#>  2:    1  484            58
#>  3:    1  664            87
#>  4:    1 1004           115
#>  5:    1 1231           120
#>  6:    1 1372           142
#>  7:    1 1582           145
#>  8:    2  118            33
#>  9:    2  484            69
#> 10:    2  664           111
#> 11:    2 1004           156
#> 12:    2 1231           172
#> 13:    2 1372           203
#> 14:    2 1582           203
#> 15:    3  118            30
#> 16:    3  484            51
#> 17:    3  664            75
#> 18:    3 1004           108
#> 19:    3 1231           115
#> 20:    3 1372           139
#> 21:    3 1582           140
#> 22:    4  118            32
#> 23:    4  484            62
#> 24:    4  664           112
#> 25:    4 1004           167
#> 26:    4 1231           179
#> 27:    4 1372           209
#> 28:    4 1582           214
#> 29:    5  118            30
#> 30:    5  484            49
#> 31:    5  664            81
#> 32:    5 1004           125
#> 33:    5 1231           142
#> 34:    5 1372           174
#> 35:    5 1582           177
#>     Tree  age circumference
```

<sup>Created on 2019-05-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
