### ISSUE TITLE
Documentation/ Examples

### ISSUE THREAD

**Issue by S-UP** [hadley/dtplyr#66]
Hi,

Thanks for the package! This indeed does speed up calculations when working with bigger datasets.

May I suggest you add a couple of examples to the readme file to make clear how a user is supposed to leverage the capabilities of this package. Also, I would appreciate a clear statement with respect to loading packages. That is, is it of any importance to follow a given order when loading the 3 packages?

Thanks!

**Comment by hadley** [comment]
Agreed. Will fix as a part of #58
