### ISSUE TITLE
Reusing variables in summarize fails for data.tables

### ISSUE THREAD

**Issue by hadley** [hadley/dtplyr#7]
Moved from https://github.com/hadley/dplyr/issues/1574, by @richierocks

To reproduce:

``` r
library(dplyr)
library(data.table)

# This works as expected
data.frame(x = 1:6, grp = gl(2, 3)) %>% 
  group_by_(~ grp) %>% 
  summarize_(minX = ~ min(x), minXPlus1 = ~ minX + 1)

# Changing to a data.table causes an error
data.table(x = 1:6, grp = gl(2, 3)) %>% 
  group_by_(~ grp) %>% 
  summarize_(minX = ~ min(x), minXPlus1 = ~ minX + 1)
## Error in `[.data.table`(`_dt`, , list(minX = min(x), minXPlus1 = minX +  : 
##   object 'minX' not found
```

---

This was tested using CRAN `dplyr`; today's devel version gives me the error:

``` r
## Error in .Call("dplyr_resolve_vars", PACKAGE = "dplyr", new_groups, names) : 
##   "dplyr_resolve_vars" not available for .Call() for package "dplyr"
```

in both the data.frame and data.table cases.

Possibly related to https://github.com/hadley/dplyr/issues/883

Presumably caused by this `data.table` issue https://github.com/Rdatatable/data.table/issues/659, though I don't know if you want to work around it on a `dplyr` level.

**Comment by richierocks** [comment]
Just having a clean up of old issues I'm mentioned in. This has been fixed (probably for a long time) so I think this can be closed.
